Feature: Chat with LLM
  As a logged-in user
  I want to be able to chat with an LLM and manage my conversation history
  So that I can get answers to my questions and refer back to previous conversations

  Scenario: Send a prompt and receive a response
    Given I am logged in and on the dashboard
    When I enter a prompt in the chat box and click "Send"
    Then I should see my prompt and the LLM's response in the chat window

  Scenario: Conversation history is saved
    Given I have completed a chat session
    When I refresh the dashboard or log in again
    Then I should see my previous session listed in the history sidebar

  Scenario: Search conversation history
    Given I have multiple saved chats
    When I enter a keyword into the history search bar
    Then only the relevant matching sessions should be displayed in the sidebar

  Scenario: Resume a conversation from history
    Given I have saved conversations in my history
    When I click on a past conversation in the sidebar
    Then the conversation should be loaded into the chat window

  Scenario: Select a specific model before sending a message
    Given I am logged in and on the dashboard
    And multiple models are available in the model dropdown
    When I select a specific model from the dropdown
    And I enter a prompt and click "Send"
    Then the response should be generated by the selected model
    And the model name should appear as a label on the response bubble

  Scenario: Compare responses from multiple models simultaneously
    Given I am logged in and on the dashboard
    When I click the "Compare Models" button
    Then the compare panel should appear with model checkboxes
    When I select two or more models and send a prompt
    Then I should see a side-by-side comparison of responses from each selected model
    And each response column should be labeled with the model name

  Scenario: Model name is displayed on assistant response bubbles
    Given I am logged in and on the dashboard
    When I send a message using a selected model
    Then the assistant response bubble should display the name of the model that generated it
