Feature: Iteration 3 - Multi-Model Backend and Chat Utilities
  As a logged-in user
  I want to select different backend LLMs, ask questions, and use chat utilities
  So that I can choose how my questions are answered and manage my messages efficiently

  Scenario: Select a backend LLM and send a prompt
    Given I am logged in and on the dashboard
    When I click the Models dropdown
    And I select a backend LLM from the available options
    And I enter a prompt and click Send
    Then the system should process the prompt using the selected backend
    And I should see the response in the chat window

  Scenario: Select a local small model and receive a response
    Given I am logged in and on the dashboard
    When I click the Models dropdown
    And I select a local small model from the available options
    And I enter a prompt asking about a local model and click Send
    Then I should receive a response generated by that local model

  Scenario: Copy response to clipboard
    Given I am logged in on the dashboard with at least one message
    When I hover over an assistant message
    And I click the Copy button
    Then the response text should be copied to the clipboard

  Scenario: Resend a user prompt
    Given I am logged in on the dashboard with a previous prompt
    When I hover over a user message
    And I click the Resend button
    Then the system should resubmit that prompt
    And I should see a new response in the chat window

  Scenario: Select response level and receive appropriately formatted answer
    Given I am logged in and on the dashboard
    When I select the "beginner" response level from the dropdown
    And I enter a complex prompt and click Send
    Then the system should return an answer using the beginner response level
    And I should see the response in the chat window
